# Generated by Django 3.0.5 on 2020-06-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Arabica', 'Arabica'), ('Conillon', 'Conillon')], default='Arabica', max_length=10)),
                ('data', models.DateField()),
                ('cotacao', models.FloatField()),
                ('variacao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MIlho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('cotacao', models.FloatField()),
                ('variacao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Soja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('cotacao', models.FloatField()),
                ('variacao', models.FloatField()),
            ],
        ),
    ]
