# Generated by Django 3.0.5 on 2020-06-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soja',
            name='cotacao',
            field=models.FloatField(verbose_name='Cotação'),
        ),
        migrations.AlterField(
            model_name='soja',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='soja',
            name='variacao',
            field=models.FloatField(verbose_name='Variação'),
        ),
    ]
