# Generated by Django 3.0.5 on 2020-06-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200607_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='cotacao',
            field=models.FloatField(verbose_name='Cotação'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='tipo',
            field=models.CharField(choices=[('Arabica', 'Arabica'), ('Conillon', 'Conillon')], default='Arabica', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='variacao',
            field=models.FloatField(verbose_name='Variação'),
        ),
        migrations.AlterField(
            model_name='milho',
            name='cotacao',
            field=models.FloatField(verbose_name='Cotação'),
        ),
        migrations.AlterField(
            model_name='milho',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='milho',
            name='variacao',
            field=models.FloatField(verbose_name='Variação'),
        ),
    ]
